char *s = N_("<b>Army Unit Selector</b>");
char *s = N_("<b>Preview</b>");
char *s = N_("Image:");
char *s = N_("Large");
char *s = N_("Select A File");
char *s = N_("Selector Editor");
char *s = N_("Shieildset:");
char *s = N_("Small");
char *s = N_("_Close");
