.TH LORDSAWAR-EDITOR "6" "June 2014" "lordsawar 0.3.0" "Games"
.SH NAME
lordsawar-editor \- Make your own scenarios for lordsawar
.SH SYNOPSIS
.B lordsawar-editor
[\fIOPTION\fR...] [\fIFILE\fR]
.SH DESCRIPTION
The LordsAWar! scenario editor lets you change nearly every facet of a scenario.  Lay down forest, rivers, lakes, mountains and more!  Place cities strategically and name them whatever you want.  Create roads to connect the cities.  Go further and design your own square terrain tiles.  Design your own graphics for armies, shields and castles.
.TP
\fB\-h\fB, \fB\-\-help\fR
Give this help list.
.PP
\fIFILE\fRs can be a saved game file (.sav), or a map (.map) file.
.SH "FILES"
.TP 28n
.I ~/.lordsawarrc
The configuration file.
.TP
.I ~/.lordsawar/
Saved game directory.
.TP
.I ~/.lordsawar/map/
Saved scenario maps directory.
.TP
.I ~/.lordsawar/army/
Saved armyset directory.
.TP
.I ~/.lordsawar/tilesets/
Saved tileset directory.
.TP
.I ~/.lordsawar/shield/
Saved shieldset directory.
.TP
.I ~/.lordsawar/citysets/
Saved cityset directory.
.SH "REPORTING BUGS"
Report bugs to <lordsawar-discuss@nongnu.org>.
.SH "SEE ALSO"
The full documentation for
.B lordsawar
is available on the web at: http://www.nongnu.org/lordsawar/manual/
