char *s = N_("<b>Scenarios</b>");
char *s = N_("<i>You can use the editor to make your own scenarios.</i>");
char *s = N_("Description:");
char *s = N_("Load Scenario");
char *s = N_("Name:");
char *s = N_("Number of Cities:");
char *s = N_("Number of Players:");
char *s = N_("_Cancel");
char *s = N_("_Load");
