_("Standard Units");
_("Pikeman");
_("A peasant equipped with a simple pike. This is not a serious enemy, but can nevertheless be fairly effective against cavalry.");
_("Soldier");
_("Archer");
_("Veteran");
_("Cavalry");
_("Catapult");
_("Heroes");
_("Barbarian");
_("Amazone");
_("Sandman");
_("Goblin Chieftain");
_("Male Orc");
_("Female Orc");
_("Imperial Troops");
_("Knight");
_("Unicorn");
_("Mage");
_("Dragon");
_("Holy Warrior");
_("Transport");
_("Frigate");
_("Monsters");
_("Greater Troll");
_("Killing Sheep");
_("Wood Face");
_("Beholder");
_("Demon Spawn");
_("Flying Hydra");
_("Green Ooze");
_("Octopus");
_("Orcs");
_("Bomb Thrower");
_("Shaman");
_("Orcish Catapult");
_("Wolf Rider");
_("Bat Rider");
_("Orcish Galeon");
_("Dreadnought");
_("default");
_("Grass");
_("Water");
_("Forest");
_("Hills");
_("Swamp");
_("Mountains");
_("Moon Blade");
_("Mace of the Zealot");
_("Defender's Helmet");
_("Scroll of Waterwalking");
_("Shield of Parrying");
_("Field Plate");
_("Healthy Cloak");
_("Ring of Endurance");
_("Wayfarer's Staff");
_("Enchanted Dagger");
_("Enchanted Sword");
_("Enchanted Axe");
_("Defense Rapier");
_("Skull Crusher");
_("Orcish Dagger");
_("Orcish Sword");
_("Magic Spear");
_("Enchanted Greatsword");
_("Orcish Greatsword");
_("Everburning Torch");
_("Dwarven Hammer");
_("Berserker Axe");
_("Elven Sword");
_("Power Halberd");
_("Baneblade");
_("Thrakil's Battleaxe");
_("Trident of the Seas");
_("Flaming Death");
_("Evening Star");
_("Sword of the Avatar");
_("Studded Armour");
_("Ranger Vest");
_("Wall Aegis");
_("Golden Shield");
_("Silver Cap");
_("Ruby Ring");
_("Golden Mask");
_("Crystal Rose");
_("Neutral");
_("Seville");
_("Illorath");
_("Almoravid");
_("Ongoladan");
_("Badajoz");
_("Xaphocles");
_("Count of Barcelona");
_("Barcelona");
_("Palma");
_("Rabat-Sale");
_("Sijilmasa");
_("Marrakesh");
_("Seville");
_("Badjoz");
_("Fez");
_("Denia");
_("Murcia");
_("Zaragoza");
_("Albarracin");
_("Pamplona");
_("Lisbon");
_("Oviedo");
_("Toledo");
_("Granada");
_("Metilla");
_("Algiers");
_("Tlemsen");
_("Oran");
_("Tangier");
_("Narbonne");
_("Tomb of Kings");
_("Silent Monastery");
_("Shrine of the Crusader");
_("Garden of Frost");
_("Small temple");
_("Tomb of Warriors");
_("Order of Spirit");
_("Cathedral");
_("House of Small Gods");
_("Druid's Home");
_("Dark Hole");
_("Dark Tower");
_("Fallen Temple");
_("Dark Dungeon");
_("Silent Lair");
_("Ruined Temple");
_("Dusty Caves");
_("Ruined Castle");
_("Old Thymiaterium");
_("Soloeis");
_("Spain 1060");
_("For you, the Emir of Seville, difficult times lie ahead.  The Muslims of Spain are divided amongst themselves and are under pressure from the Christians in the North such as the Count of Barcelona. From out the Sahara desert have appeared the Almoravids who may well be strong enough to check the Christians but are likely to gobble you up in the process. Surely the other Muslims  such as the Emir of Badajoz will realize they need to unite under your overlordship?....");
_("Player Neutral died.");
_("Player Seville died.");
_("Player Almoravid died.");
_("Player Badajoz died.");
_("Player Count of Barcelona died.");
_("Player Seville has won!");
_("Player Almoravid has won!");
_("Player Badajoz has won!");
_("Player Count of Barcelona has won!");
_("Neutral");
_("Carthage");
_("Hanibal");
_("Rome");
_("Fabius");
_("Roma");
_("Taras");
_("Gades");
_("Carthage");
_("New Carthage");
_("Numantia");
_("Saguntum");
_("Capua");
_("Syracuse");
_("Ausculum");
_("Croton");
_("Clusium");
_("Lilybaeum");
_("Lixus");
_("Carales");
_("Hadrumentum");
_("Placentia");
_("Massillia");
_("Tarraco");
_("Leptis");
_("Messana");
_("Gegovia");
_("Olisippo");
_("Monastery of Io");
_("Temple of Belisama");
_("Temple of Apollo");
_("Shrine of the Mists");
_("Temple of Jupitor");
_("Temple of Hammon");
_("The Lost City");
_("Zelasen's Tomb");
_("Ruined City");
_("Weird Ruins");
_("Keltic Barrow");
_("Abandoned Temple");
_("Burial Mound");
_("Misty Maze");
_("Tumulus");
_("The Sibyl's Cave");
_("The Second Punic War");
_("Carthage has lost her dominance on the sea and you, Hannibal, are convinced that the only hope of avoiding the destruction of your city is to move to the attack - thru Spain and across the Alps.");
_("Player Neutral died.");
_("Player Carthage died.");
_("Player Rome died.");
_("Player Carthage has won!");
_("Player Rome has won!");
_("If New Carthage falls...");
_("Neutrale");
_("Northumbria");
_("Ingaron");
_("T' Pictish King");
_("Glathros");
_("Mercia");
_("Andaradan");
_("The High King");
_("Waldorath");
_("Wessex");
_("Cynethryth");
_("York");
_("Scone");
_("Leicester");
_("Tara");
_("Winchester");
_("Cork");
_("Mayo");
_("London");
_("Whithorn");
_("Litchfield");
_("Dunedin");
_("Dingwall");
_("Thurso");
_("Exeter");
_("Obar Dheathan");
_("Whitby");
_("Dunadd");
_("Hastings");
_("Gloucester");
_("Hill of Tara");
_("Canterbury");
_("Iona");
_("Lidisfarne");
_("Downpatrick");
_("Verulamium");
_("Stonehenge");
_("Carrowmore");
_("Gleninsheen");
_("Drombeg");
_("Dolmen of the four Maols");
_("Kilcloony Dolmen");
_("The Hurlers");
_("Long Meg and her Daughters");
_("The Rollright Stones");
_("Temple Wood");
_("Sunhoney");
_("Corrymoney");
_("Tinkinswood");
_("Bryn Cader Faner");
_("Pentre Ifan");
_("Gilling Long Cairn");
_("Britain 802");
_("The 9th century opens with the isles divided into tribes and petty kingdoms but several are already emerging as front runners in a struggle for hegemony. To the West the High King of Ireland. To the North the Pictish King. To the south the Kings of Wessex and Mercia. And in the middle you, the King of Northumbria, is surrounded by enemies...");
_("Player Neutral died.");
_("You have lost!!");
_("Despair at the desolation of defeat!");
_("The Pictish King is dead.");
_("The King of Mercia has fled into exile.");
_("The High King has been killed.");
_("The king of Wessex has been killed.");
_("Northumbria has won!");
_("The King of the Picts has won!");
_("Player Ulf has won!");
_("Player James has won!");
_("Player Vibhu has won!");
_("defeat");
_("Neutral");
_("Arkadia");
_("Alcanen");
_("Gray Horde");
_("Omelan");
_("Imperium");
_("Thastophere");
_("Montserrat");
_("Darcor");
_("Watchtower");
_("Brunnaburgh");
_("Coldpeak");
_("Kurigalzu");
_("Karhain");
_("Pelerine");
_("Moonshine");
_("Hellgate");
_("Trales");
_("Noname");
_("Atena");
_("Noname");
_("Druid's Home");
_("Small temple");
_("Holy Ghost's Archive");
_("House of Small Gods");
_("Holy Wood");
_("Shrine of Power");
_("Peasant's church");
_("Garden of Peace");
_("Order of Fire");
_("Monastery of Io");
_("Silent Monastery");
_("Offler's Temple");
_("Sanctuary of the Fallen");
_("Holy Place");
_("Tomb of Kings");
_("Dark Tower");
_("Black Tomb");
_("Dark Dungeon");
_("Fallen Temple");
_("Weird Ruins");
_("Dark Hole");
_("Dusty Caves");
_("Abandoned Village");
_("Ghost Town");
_("Silent Farm");
_("Ruined Temple");
_("Deserted Monastery");
_("Ruined City");
_("Ruined Castle");
_("Misty Maze");
_("Khan's tomb");
_("Target");
_("The two AI players will treat you as their target and will get extra advantages on top of that. But you're better than the two of them aren't you?");
_("Player Neutral died.");
_("Player Arkadia died.");
_("Player Gray Horde died.");
_("Player Imperium died.");
_("Player Arkadia has won!");
_("Player Gray Horde has won!");
_("Player Imperium has won!");
_("Neutral");
_("Good guy");
_("Ingorian");
_("Evil Overlord");
_("Eldaragon");
_("The Shire");
_("Dragonbone");
_("Old Tower");
_("Ruined City");
_("Tomb of the old king");
_("Mysterious hole");
_("Hydra's Lair");
_("Dragon's lair");
_("Tutorial and Testing");
_("This scenario is the Freelords testing Tutorial. Its pourpose is to demonstrate the advanced features of Freelords.");
_("The introduction for the player.");
_("This is the tutorial of FreeLords. Though it is called tutorial, one of the main aims is to demonstrate some advanced abilities of FreeLords, such as events.");
_("BTW: If you like (or better: don't yet like) what you see here, we are always looking for coders, graphics artists and (new) map designers! Enough ads, let us start with the game.");
_("For ages you and your ancestors have lived peacefully in the lovely Shire. Nothing disturbed the quietness here until some months ago...");
_("Orcs appeared.");
_("The foul creatures infested the old tower in the swamp and built up a fortress there, growing more and more powerful. And aggressive. During one of their raids, they destroyed a village close to the swamp. So you decided to drive them out.");
_("But the army under the command of your most able leader just vanished in the swamps.");
_("\"Huh, Where am I??\"");
_("Player has killed the Orc that appeared at the introductory event.");
_("When you search the orc, you find some recently used digging tools.");
_("After one round, an orc appears at the ruin next to the player's city and the player is warned of Orcish sappers.");
_("\"We have come through. Look, the Weakling's castle is there.\"");
_("\"My Lord, the orcs have been digging a tunnel to our castle. You must destroy it!\"");
_("\"Die, human!\"");
_("\"Argh.\"");
_("Your advisor informs you: \"If you want to fight the Orcish hordes, it would be wise to visit the tomb of your father to the west. He had several powerful artefacts placed there.\"");
_("When the player searches the temple to the east, he gets some artefacts. This event is enabled by the previous one.");
_("The priests have heard of your task and awaited your coming. They present you some artefacts of your father.");
_("When the ruin to the west of the city is searched, remove the appearance of orcs (foolowing events)");
_("You flood the tunnel with the help of the nearby lake. The danger by the orcs should be banned for now. All that is left is getting rid of the Orcish fortress.");
_("Maybe you want to search the lair to the south of your town now. It is rumored that a lot of gold can be found there.");
_("First orcs come through the tunnel.");
_("\"Where are our scouts? Humans!!\"");
_("Again, orcs come through the tunnel.");
_("\"Let's raze the city!!\"");
_("The Orcish invasion starts.");
_("\"Hunt them down!\"");
_("Now many orcs come out of the tunnel.");
_("\"The humans don't stand a chance. Let's crush them!\"");
_("After the ruin is searched (event is activated there) the neutral town offers its services.");
_("The rumours of your deeds have spread. As a result, the nearby town of Dragonbone decides to join you.");
_("Hydra's Lair is searched, player gets some gold.");
_("After you have slain the pair of hydras that occupied the cave, you find a valuable sword and a hidden treasure worth 2000 gold.");
_("The player has been killed.");
_("Though you managed to survived the Orcish raids, you had to escape the land and find some fortune at other places. Meanwhile, the orcs devastated  the lands and ruined the towns.");
_("YOU LOST!");
_("The Orcish town is conquered, the game is won.");
_("You captured the fortress that was so well defended by the orcs. When their remaining troops that ravage the lands hear from this, they panic and run. The Evil is defeated here. Congratulations, the tutorial is hereby finished.");
_("YOU WIN!");
